### PR TITLE
Solving Int vs other indexing problem (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by Tokazama**
This is a minor rethinking of the current approach.

1. Allow any `AbstractVector` to be an index
1. Only `AcceleratedVector`s are guaranteed to go through reverse indexing even with `Int`.
1. Default behavior is to use `to_index` downstream from `to_indices`.

This solves several problems.

1. We aren't backed into a corner with only allowing `AcceleratedVector`, so anyone can extend the `IndexedDimsArray` type if they implement a custom `AbstractVector`.
2. Because the default is to use `to_index` we also inherit any future optimizations from base that `AcceleratedArrays` might not have.
3. This also allows faster linear indexing if given normal indices and appropariate for the parent type.

Note: I haven't fully worked out bugs yet so don't merge. But I wanted feedback on this approach before going all in with it.

### CODE REVIEW

**Comment by iamed2** [comment]
Currently this degrades to the type of the parent. I think we're going to have to implement our own getindex in order to avoid that, which means to_indices isn't particularly useful to us. I'm working on that locally, but I should push a branch with my current state.

My thought on fast indexing for the underlying parent is to provide a wrapper type that allows indexing into the underlying array with pass-through indexing but returning a new IndexedDimsArray. This wrapper could be available as a property of the IndexedDimsArray, perhaps. If you want linear indexing or anything else that vectorizes the output, you can call `parent` and index into that.

**Comment by Tokazama** [comment]
So would than mean that in order to do something like `arr[1:end]` on a multidimensional array we'd have to actually do `arr.parent[1:end]`?

**Comment by iamed2** [comment]
Yes

**Comment by Tokazama** [comment]
I'll close this for now as it seems you have a different direction in mind.

**Pull request closed without merging**
